#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# Filename    : zusys.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Jan 14 15:29:37 CET 2019
# SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved. 
#
# usage: zusys.sh [-help]
# usage: zusys.sh [-lib_map_path]
# usage: zusys.sh [-noclean_files]
# usage: zusys.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'zusys.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_1 axi_vip_v1_1_1 zynq_ultra_ps_e_vip_v1_0_1 lib_pkg_v1_0_2 fifo_generator_v13_2_1 lib_fifo_v1_0_10 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_17 axi_sg_v4_1_8 axi_dma_v7_1_16 xlconstant_v1_1_3 xlconcat_v2_1_1 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_15 axis_subset_converter_v1_1_15 generic_baseblocks_v2_1_0 axi_data_fifo_v2_1_14 axi_register_slice_v2_1_15 axi_protocol_converter_v2_1_15)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "zusys.sh - Script generated by export_simulation (Vivado v2017.4 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zusys/ipshared/8125/src/ddrspi_master.vhd" \
    "$ref_dir/../../../bd/zusys/ipshared/8125/src/SC0808BF.vhd" \
    "$ref_dir/../../../bd/zusys/ip/zusys_SC0808BF_0_0/sim/zusys_SC0808BF_0_0.vhd" \
    "$ref_dir/../../../bd/zusys/ipshared/5e77/hdl/axis_live_audio_v1_0.vhd" \
    "$ref_dir/../../../bd/zusys/ip/zusys_axis_live_audio_0_0/sim/zusys_axis_live_audio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zusys/ip/zusys_proc_sys_reset_0_0/sim/zusys_proc_sys_reset_0_0.vhd" \
    "$ref_dir/../../../bd/zusys/ip/zusys_proc_sys_reset_1_0/sim/zusys_proc_sys_reset_1_0.vhd" \
    "$ref_dir/../../../bd/zusys/ip/zusys_vio_general_0/sim/zusys_vio_general_0.vhd" \
    "$ref_dir/../../../bd/zusys/ip/zusys_vio_rgpio_0/sim/zusys_vio_rgpio_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_1 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/3b24/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_1 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a16a/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_1 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_zynq_ultra_ps_e_0_0/sim/zusys_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zusys/ip/zusys_proc_sys_reset_2_0/sim/zusys_proc_sys_reset_2_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/5c35/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_1 $vhdlan_opts \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_10 $vhdlan_opts \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/f10a/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_17 $vhdlan_opts \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/71f3/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_8 $vhdlan_opts \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/5f94/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_16 $vhdlan_opts \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bf8c/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zusys/ip/zusys_axi_dma_0_0/sim/zusys_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/sim/bd_2abc.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/786b/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_2abc_s00a2s_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_2abc_s01a2s_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_2abc_s02a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/92d2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_29/sim/bd_2abc_m00s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/258c/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_35/sim/bd_2abc_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_30/sim/bd_2abc_m00arn_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_31/sim/bd_2abc_m00rn_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_32/sim/bd_2abc_m00awn_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_33/sim/bd_2abc_m00wn_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_34/sim/bd_2abc_m00bn_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_2abc_sawn_1.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_2abc_swn_1.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_28/sim/bd_2abc_sbn_1.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/8ad6/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_2abc_s02mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0f5f/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_2abc_s02tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/925a/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_2abc_s02sic_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_2abc_sarn_1.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_2abc_srn_1.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_2abc_s01mmu_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_2abc_s01tr_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_2abc_s01sic_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_2abc_sarn_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_2abc_srn_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_2abc_sawn_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_2abc_swn_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_2abc_sbn_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_2abc_s00mmu_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_2abc_s00tr_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_2abc_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/1b0c/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_2abc_arsw_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_2abc_rsw_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_2abc_awsw_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_2abc_wsw_0.sv" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_2abc_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0750/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_2abc_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_2abc_psr_aclk_0.vhd" \
    "$ref_dir/../../../bd/zusys/ip/zusys_smartconnect_0_0/sim/zusys_smartconnect_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_xlconcat_0_0/sim/zusys_xlconcat_0_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_top_0_0/dma_killer_project.srcs/sources_1/ip/fifo_generator_0/sim/fifo_generator_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zusys/ipshared/cbce/dma_killer_project.srcs/sources_1/new/common_pkg.vhd" \
    "$ref_dir/../../../bd/zusys/ipshared/cbce/dma_killer_project.srcs/sources_1/new/M00_AXIS.vhd" \
    "$ref_dir/../../../bd/zusys/ipshared/cbce/dma_killer_project.srcs/sources_1/new/S00_AXIS.vhd" \
    "$ref_dir/../../../bd/zusys/ipshared/cbce/dma_killer_project.srcs/sources_1/new/controller.vhd" \
    "$ref_dir/../../../bd/zusys/ipshared/cbce/dma_killer_project.srcs/sources_1/new/top.vhd" \
    "$ref_dir/../../../bd/zusys/ip/zusys_top_0_0/sim/zusys_top_0_0.vhd" \
    "$ref_dir/../../../bd/zusys/ip/zusys_ila_0_0/sim/zusys_ila_0_0.vhd" \
    "$ref_dir/../../../bd/zusys/ip/zusys_ila_tx_0_0/sim/zusys_ila_tx_0_0.vhd" \
    "$ref_dir/../../../bd/zusys/sim/zusys.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cd45/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_k_1/hdl/tdata_zusys_auto_ss_k_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_k_1/hdl/tuser_zusys_auto_ss_k_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_k_1/hdl/tstrb_zusys_auto_ss_k_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_k_1/hdl/tkeep_zusys_auto_ss_k_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_k_1/hdl/tid_zusys_auto_ss_k_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_k_1/hdl/tdest_zusys_auto_ss_k_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_k_1/hdl/tlast_zusys_auto_ss_k_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_subset_converter_v1_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6ad2/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_k_1/hdl/top_zusys_auto_ss_k_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_k_1/sim/zusys_auto_ss_k_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_slid_1/hdl/tdata_zusys_auto_ss_slid_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_slid_1/hdl/tuser_zusys_auto_ss_slid_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_slid_1/hdl/tstrb_zusys_auto_ss_slid_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_slid_1/hdl/tkeep_zusys_auto_ss_slid_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_slid_1/hdl/tid_zusys_auto_ss_slid_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_slid_1/hdl/tdest_zusys_auto_ss_slid_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_slid_1/hdl/tlast_zusys_auto_ss_slid_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_slid_1/hdl/top_zusys_auto_ss_slid_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_slid_1/sim/zusys_auto_ss_slid_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_u_1/hdl/tdata_zusys_auto_ss_u_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_u_1/hdl/tuser_zusys_auto_ss_u_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_u_1/hdl/tstrb_zusys_auto_ss_u_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_u_1/hdl/tkeep_zusys_auto_ss_u_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_u_1/hdl/tid_zusys_auto_ss_u_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_u_1/hdl/tdest_zusys_auto_ss_u_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_u_1/hdl/tlast_zusys_auto_ss_u_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_u_1/hdl/top_zusys_auto_ss_u_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_u_1/sim/zusys_auto_ss_u_1.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_k_0/hdl/tdata_zusys_auto_ss_k_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_k_0/hdl/tuser_zusys_auto_ss_k_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_k_0/hdl/tstrb_zusys_auto_ss_k_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_k_0/hdl/tkeep_zusys_auto_ss_k_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_k_0/hdl/tid_zusys_auto_ss_k_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_k_0/hdl/tdest_zusys_auto_ss_k_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_k_0/hdl/tlast_zusys_auto_ss_k_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_k_0/hdl/top_zusys_auto_ss_k_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_k_0/sim/zusys_auto_ss_k_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_slid_0/hdl/tdata_zusys_auto_ss_slid_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_slid_0/hdl/tuser_zusys_auto_ss_slid_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_slid_0/hdl/tstrb_zusys_auto_ss_slid_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_slid_0/hdl/tkeep_zusys_auto_ss_slid_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_slid_0/hdl/tid_zusys_auto_ss_slid_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_slid_0/hdl/tdest_zusys_auto_ss_slid_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_slid_0/hdl/tlast_zusys_auto_ss_slid_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_slid_0/hdl/top_zusys_auto_ss_slid_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_slid_0/sim/zusys_auto_ss_slid_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_u_0/hdl/tdata_zusys_auto_ss_u_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_u_0/hdl/tuser_zusys_auto_ss_u_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_u_0/hdl/tstrb_zusys_auto_ss_u_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_u_0/hdl/tkeep_zusys_auto_ss_u_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_u_0/hdl/tid_zusys_auto_ss_u_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_u_0/hdl/tdest_zusys_auto_ss_u_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_u_0/hdl/tlast_zusys_auto_ss_u_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_u_0/hdl/top_zusys_auto_ss_u_0.v" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_ss_u_0/sim/zusys_auto_ss_u_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_14 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/9909/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/3ed1/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ff69/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" +incdir+"$ref_dir/../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zusys/ip/zusys_auto_pc_0/sim/zusys_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.zusys xil_defaultlib.glbl -o zusys_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./zusys_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./zusys.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key zusys_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc zusys_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./zusys.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: zusys.sh [-help]\n\
Usage: zusys.sh [-lib_map_path]\n\
Usage: zusys.sh [-reset_run]\n\
Usage: zusys.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
