webtalk_init -webtalk_dir /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-01-15 18:19:43" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174116392_174116393_210659485_826" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fqa4m1g9t80b9sk4plq41vkekd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_28" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "28" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1250.345 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.221 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1547556724000" -context "sdk\\\\application/1547556724000"
webtalk_add_data -client sdk -key hwid -value "1547400951000" -context "sdk\\\\application/1547556724000"
webtalk_add_data -client sdk -key bspid -value "1547471363000" -context "sdk\\\\application/1547556724000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1547556724000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1547556724000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1547556724000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1547556724000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1547556724000"
webtalk_add_data -client sdk -key Procused -value "psu_cortexa53" -context "sdk\\\\application/1547556724000"
webtalk_add_data -client sdk -key projSize -value "244.4140625" -context "sdk\\\\application/1547556724000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1547572783864"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1547572783864"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1547572783864"
webtalk_add_data -client sdk -key DebugCount -value "207" -context "sdk\\\\bsp/1547572783864"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1547572783864"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1547572783864"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1547572783864"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1547572783864"
webtalk_transmit -clientid 3564873011 -regid "174116392_174116393_210659485_826" -xml /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
