# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/_i_io.xdc

# XDC: imports/constraints/_i_bitgen.xdc

# XDC: imports/constraints/vivado_target.xdc

# Block Designs: bd/zusys/zusys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys || ORIG_REF_NAME==zusys} -quiet] -quiet

# IP: bd/zusys/ip/zusys_zynq_ultra_ps_e_0_0/zusys_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==zusys_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_proc_sys_reset_2_0/zusys_proc_sys_reset_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_proc_sys_reset_2_0 || ORIG_REF_NAME==zusys_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_axi_dma_0_0/zusys_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_axi_dma_0_0 || ORIG_REF_NAME==zusys_axi_dma_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_smartconnect_0_0/zusys_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_smartconnect_0_0 || ORIG_REF_NAME==zusys_smartconnect_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xlconcat_0_0/zusys_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_xlconcat_0_0 || ORIG_REF_NAME==zusys_xlconcat_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_axi_interconnect_0_0/zusys_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_axi_interconnect_0_0 || ORIG_REF_NAME==zusys_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_top_0_0/zusys_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_top_0_0 || ORIG_REF_NAME==zusys_top_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_ila_0_0/zusys_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_ila_0_0 || ORIG_REF_NAME==zusys_ila_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_ila_tx_0_0/zusys_ila_tx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_ila_tx_0_0 || ORIG_REF_NAME==zusys_ila_tx_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_axis_interconnect_0_0/zusys_axis_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_axis_interconnect_0_0 || ORIG_REF_NAME==zusys_axis_interconnect_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_axis_interconnect_0_1/zusys_axis_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_axis_interconnect_0_1 || ORIG_REF_NAME==zusys_axis_interconnect_0_1} -quiet] -quiet

# IP: bd/zusys/ip/zusys_dma_killer_0_0/zusys_dma_killer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_dma_killer_0_0 || ORIG_REF_NAME==zusys_dma_killer_0_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xbar_0/zusys_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_xbar_0 || ORIG_REF_NAME==zusys_xbar_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_xbar_1/zusys_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_xbar_1 || ORIG_REF_NAME==zusys_xbar_1} -quiet] -quiet

# IP: bd/zusys/ip/zusys_ila_0_1/zusys_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_ila_0_1 || ORIG_REF_NAME==zusys_ila_0_1} -quiet] -quiet

# IP: bd/zusys/ip/zusys_auto_ss_k_2/zusys_auto_ss_k_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_auto_ss_k_2 || ORIG_REF_NAME==zusys_auto_ss_k_2} -quiet] -quiet

# IP: bd/zusys/ip/zusys_auto_ss_slidr_2/zusys_auto_ss_slidr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_auto_ss_slidr_2 || ORIG_REF_NAME==zusys_auto_ss_slidr_2} -quiet] -quiet

# IP: bd/zusys/ip/zusys_auto_ss_u_2/zusys_auto_ss_u_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_auto_ss_u_2 || ORIG_REF_NAME==zusys_auto_ss_u_2} -quiet] -quiet

# IP: bd/zusys/ip/zusys_auto_ss_k_1/zusys_auto_ss_k_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_auto_ss_k_1 || ORIG_REF_NAME==zusys_auto_ss_k_1} -quiet] -quiet

# IP: bd/zusys/ip/zusys_auto_ss_slidr_1/zusys_auto_ss_slidr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_auto_ss_slidr_1 || ORIG_REF_NAME==zusys_auto_ss_slidr_1} -quiet] -quiet

# IP: bd/zusys/ip/zusys_auto_ss_u_1/zusys_auto_ss_u_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_auto_ss_u_1 || ORIG_REF_NAME==zusys_auto_ss_u_1} -quiet] -quiet

# IP: bd/zusys/ip/zusys_s_arb_req_suppress_concat_0/zusys_s_arb_req_suppress_concat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_s_arb_req_suppress_concat_0 || ORIG_REF_NAME==zusys_s_arb_req_suppress_concat_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_auto_ss_k_0/zusys_auto_ss_k_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_auto_ss_k_0 || ORIG_REF_NAME==zusys_auto_ss_k_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_auto_ss_slidr_0/zusys_auto_ss_slidr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_auto_ss_slidr_0 || ORIG_REF_NAME==zusys_auto_ss_slidr_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_auto_ss_u_0/zusys_auto_ss_u_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_auto_ss_u_0 || ORIG_REF_NAME==zusys_auto_ss_u_0} -quiet] -quiet

# IP: bd/zusys/ip/zusys_auto_pc_0/zusys_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zusys_auto_pc_0 || ORIG_REF_NAME==zusys_auto_pc_0} -quiet] -quiet

# XDC: bd/zusys/zusys_ooc.xdc
