# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xczu9eg-ffvc900-1-i-es1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.cache/wt [current_project]
set_property parent.project_path /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths /home/matt/workspace/StarterKit/board_files [current_project]
set_property board_part trenz.biz:te0808_es1_tebf0808:part0:2.0 [current_project]
set_property ip_repo_paths {
  /home/matt/Git/dma_issue_demonstrator/ip_lib
  /home/matt/Git/dma_issue_demonstrator/dma_killer_project
} [current_project]
set_property ip_output_repo /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/hdl/zusys_wrapper.vhd
add_files /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/zusys.bd
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_zynq_ultra_ps_e_0_0/zusys_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_zynq_ultra_ps_e_0_0/zusys_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_proc_sys_reset_2_0/zusys_proc_sys_reset_2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_proc_sys_reset_2_0/zusys_proc_sys_reset_2_0.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_proc_sys_reset_2_0/zusys_proc_sys_reset_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_axi_dma_0_0/zusys_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_axi_dma_0_0/zusys_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_axi_dma_0_0/zusys_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_10/bd_2abc_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_19/bd_2abc_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_25/bd_2abc_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_29/bd_2abc_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_30/bd_2abc_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_31/bd_2abc_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_32/bd_2abc_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_33/bd_2abc_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_34/bd_2abc_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_26/bd_2abc_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_27/bd_2abc_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_28/bd_2abc_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_20/bd_2abc_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_21/bd_2abc_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_11/bd_2abc_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_12/bd_2abc_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_13/bd_2abc_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_14/bd_2abc_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_15/bd_2abc_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_2/bd_2abc_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_3/bd_2abc_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_4/bd_2abc_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_5/bd_2abc_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_6/bd_2abc_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_1/bd_2abc_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_1/bd_2abc_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_top_0_0/dma_killer_project.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_synthesis false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_ila_0_0/zusys_ila_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_ila_tx_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_ila_tx_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_ila_tx_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_ila_tx_0_0/zusys_ila_tx_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_dma_killer_0_0/dma_killer_project.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_xbar_0/zusys_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_xbar_1/zusys_xbar_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_ila_0_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_ila_0_1/zusys_ila_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_auto_ss_k_2/zusys_auto_ss_k_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_auto_ss_slidr_2/zusys_auto_ss_slidr_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_auto_ss_u_2/zusys_auto_ss_u_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_auto_ss_k_1/zusys_auto_ss_k_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_auto_ss_slidr_1/zusys_auto_ss_slidr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_auto_ss_u_1/zusys_auto_ss_u_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_auto_ss_k_0/zusys_auto_ss_k_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_auto_ss_slidr_0/zusys_auto_ss_slidr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_auto_ss_u_0/zusys_auto_ss_u_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/ip/zusys_auto_pc_0/zusys_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/sources_1/bd/zusys/zusys_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/constrs_1/imports/constraints/vivado_target.xdc
set_property used_in_implementation false [get_files /home/matt/Git/dma_issue_demonstrator/te0808_project/te0808_project.srcs/constrs_1/imports/constraints/vivado_target.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top zusys_wrapper -part xczu9eg-ffvc900-1-i-es1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef zusys_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file zusys_wrapper_utilization_synth.rpt -pb zusys_wrapper_utilization_synth.pb"
