vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib
vlib modelsim_lib/msim/xpm
vlib modelsim_lib/msim/lib_cdc_v1_0_2
vlib modelsim_lib/msim/proc_sys_reset_v5_0_12
vlib modelsim_lib/msim/axi_infrastructure_v1_1_0
vlib modelsim_lib/msim/smartconnect_v1_0
vlib modelsim_lib/msim/axi_protocol_checker_v2_0_1
vlib modelsim_lib/msim/axi_vip_v1_1_1
vlib modelsim_lib/msim/zynq_ultra_ps_e_vip_v1_0_1
vlib modelsim_lib/msim/lib_pkg_v1_0_2
vlib modelsim_lib/msim/fifo_generator_v13_2_1
vlib modelsim_lib/msim/lib_fifo_v1_0_10
vlib modelsim_lib/msim/lib_srl_fifo_v1_0_2
vlib modelsim_lib/msim/axi_datamover_v5_1_17
vlib modelsim_lib/msim/axi_sg_v4_1_8
vlib modelsim_lib/msim/axi_dma_v7_1_16
vlib modelsim_lib/msim/xlconstant_v1_1_3
vlib modelsim_lib/msim/xlconcat_v2_1_1
vlib modelsim_lib/msim/axis_infrastructure_v1_1_0
vlib modelsim_lib/msim/axis_register_slice_v1_1_15
vlib modelsim_lib/msim/axis_subset_converter_v1_1_15
vlib modelsim_lib/msim/generic_baseblocks_v2_1_0
vlib modelsim_lib/msim/axi_data_fifo_v2_1_14
vlib modelsim_lib/msim/axi_register_slice_v2_1_15
vlib modelsim_lib/msim/axi_protocol_converter_v2_1_15

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
vmap xpm modelsim_lib/msim/xpm
vmap lib_cdc_v1_0_2 modelsim_lib/msim/lib_cdc_v1_0_2
vmap proc_sys_reset_v5_0_12 modelsim_lib/msim/proc_sys_reset_v5_0_12
vmap axi_infrastructure_v1_1_0 modelsim_lib/msim/axi_infrastructure_v1_1_0
vmap smartconnect_v1_0 modelsim_lib/msim/smartconnect_v1_0
vmap axi_protocol_checker_v2_0_1 modelsim_lib/msim/axi_protocol_checker_v2_0_1
vmap axi_vip_v1_1_1 modelsim_lib/msim/axi_vip_v1_1_1
vmap zynq_ultra_ps_e_vip_v1_0_1 modelsim_lib/msim/zynq_ultra_ps_e_vip_v1_0_1
vmap lib_pkg_v1_0_2 modelsim_lib/msim/lib_pkg_v1_0_2
vmap fifo_generator_v13_2_1 modelsim_lib/msim/fifo_generator_v13_2_1
vmap lib_fifo_v1_0_10 modelsim_lib/msim/lib_fifo_v1_0_10
vmap lib_srl_fifo_v1_0_2 modelsim_lib/msim/lib_srl_fifo_v1_0_2
vmap axi_datamover_v5_1_17 modelsim_lib/msim/axi_datamover_v5_1_17
vmap axi_sg_v4_1_8 modelsim_lib/msim/axi_sg_v4_1_8
vmap axi_dma_v7_1_16 modelsim_lib/msim/axi_dma_v7_1_16
vmap xlconstant_v1_1_3 modelsim_lib/msim/xlconstant_v1_1_3
vmap xlconcat_v2_1_1 modelsim_lib/msim/xlconcat_v2_1_1
vmap axis_infrastructure_v1_1_0 modelsim_lib/msim/axis_infrastructure_v1_1_0
vmap axis_register_slice_v1_1_15 modelsim_lib/msim/axis_register_slice_v1_1_15
vmap axis_subset_converter_v1_1_15 modelsim_lib/msim/axis_subset_converter_v1_1_15
vmap generic_baseblocks_v2_1_0 modelsim_lib/msim/generic_baseblocks_v2_1_0
vmap axi_data_fifo_v2_1_14 modelsim_lib/msim/axi_data_fifo_v2_1_14
vmap axi_register_slice_v2_1_15 modelsim_lib/msim/axi_register_slice_v2_1_15
vmap axi_protocol_converter_v2_1_15 modelsim_lib/msim/axi_protocol_converter_v2_1_15

vlog -work xil_defaultlib -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -64 -93 \
"/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/zusys/ipshared/8125/src/ddrspi_master.vhd" \
"../../../bd/zusys/ipshared/8125/src/SC0808BF.vhd" \
"../../../bd/zusys/ip/zusys_SC0808BF_0_0/sim/zusys_SC0808BF_0_0.vhd" \
"../../../bd/zusys/ipshared/5e77/hdl/axis_live_audio_v1_0.vhd" \
"../../../bd/zusys/ip/zusys_axis_live_audio_0_0/sim/zusys_axis_live_audio_0_0.vhd" \

vcom -work lib_cdc_v1_0_2 -64 -93 \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work proc_sys_reset_v5_0_12 -64 -93 \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/zusys/ip/zusys_proc_sys_reset_0_0/sim/zusys_proc_sys_reset_0_0.vhd" \
"../../../bd/zusys/ip/zusys_proc_sys_reset_1_0/sim/zusys_proc_sys_reset_1_0.vhd" \
"../../../bd/zusys/ip/zusys_vio_general_0/sim/zusys_vio_general_0.vhd" \
"../../../bd/zusys/ip/zusys_vio_rgpio_0/sim/zusys_vio_rgpio_0.vhd" \

vlog -work axi_infrastructure_v1_1_0 -64 -incr "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work smartconnect_v1_0 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv" \

vlog -work axi_protocol_checker_v2_0_1 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/3b24/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \

vlog -work axi_vip_v1_1_1 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a16a/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work zynq_ultra_ps_e_vip_v1_0_1 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zusys/ip/zusys_zynq_ultra_ps_e_0_0/sim/zusys_zynq_ultra_ps_e_0_0_vip_wrapper.v" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/zusys/ip/zusys_proc_sys_reset_2_0/sim/zusys_proc_sys_reset_2_0.vhd" \

vcom -work lib_pkg_v1_0_2 -64 -93 \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \

vlog -work fifo_generator_v13_2_1 -64 -incr "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/5c35/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_1 -64 -93 \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_1 -64 -incr "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.v" \

vcom -work lib_fifo_v1_0_10 -64 -93 \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/f10a/hdl/lib_fifo_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_2 -64 -93 \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work axi_datamover_v5_1_17 -64 -93 \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/71f3/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vcom -work axi_sg_v4_1_8 -64 -93 \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/5f94/hdl/axi_sg_v4_1_rfs.vhd" \

vcom -work axi_dma_v7_1_16 -64 -93 \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bf8c/hdl/axi_dma_v7_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/zusys/ip/zusys_axi_dma_0_0/sim/zusys_axi_dma_0_0.vhd" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/sim/bd_2abc.v" \

vlog -work smartconnect_v1_0 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/786b/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_2abc_s00a2s_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_2abc_s01a2s_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_2abc_s02a2s_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/92d2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_29/sim/bd_2abc_m00s2a_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/258c/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_35/sim/bd_2abc_m00e_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_30/sim/bd_2abc_m00arn_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_31/sim/bd_2abc_m00rn_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_32/sim/bd_2abc_m00awn_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_33/sim/bd_2abc_m00wn_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_34/sim/bd_2abc_m00bn_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_2abc_sawn_1.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_2abc_swn_1.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_28/sim/bd_2abc_sbn_1.sv" \

vlog -work smartconnect_v1_0 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/8ad6/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_2abc_s02mmu_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0f5f/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_2abc_s02tr_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/925a/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_2abc_s02sic_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_2abc_sarn_1.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_2abc_srn_1.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_2abc_s01mmu_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_2abc_s01tr_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_2abc_s01sic_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_2abc_sarn_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_2abc_srn_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_2abc_sawn_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_2abc_swn_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_2abc_sbn_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_2abc_s00mmu_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_2abc_s00tr_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_2abc_s00sic_0.sv" \

vlog -work smartconnect_v1_0 -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/1b0c/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L zynq_ultra_ps_e_vip_v1_0_1 -L xil_defaultlib -L xilinx_vip "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_2abc_arsw_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_2abc_rsw_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_2abc_awsw_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_2abc_wsw_0.sv" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_2abc_bsw_0.sv" \

vlog -work xlconstant_v1_1_3 -64 -incr "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0750/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_2abc_one_0.v" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_2abc_psr_aclk_0.vhd" \
"../../../bd/zusys/ip/zusys_smartconnect_0_0/sim/zusys_smartconnect_0_0.vhd" \

vlog -work xlconcat_v2_1_1 -64 -incr "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zusys/ip/zusys_xlconcat_0_0/sim/zusys_xlconcat_0_0.v" \
"../../../bd/zusys/ip/zusys_top_0_0/dma_killer_project.srcs/sources_1/ip/fifo_generator_0/sim/fifo_generator_0.v" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/zusys/ipshared/cbce/dma_killer_project.srcs/sources_1/new/common_pkg.vhd" \
"../../../bd/zusys/ipshared/cbce/dma_killer_project.srcs/sources_1/new/M00_AXIS.vhd" \
"../../../bd/zusys/ipshared/cbce/dma_killer_project.srcs/sources_1/new/S00_AXIS.vhd" \
"../../../bd/zusys/ipshared/cbce/dma_killer_project.srcs/sources_1/new/controller.vhd" \
"../../../bd/zusys/ipshared/cbce/dma_killer_project.srcs/sources_1/new/top.vhd" \
"../../../bd/zusys/ip/zusys_top_0_0/sim/zusys_top_0_0.vhd" \
"../../../bd/zusys/ip/zusys_ila_0_0/sim/zusys_ila_0_0.vhd" \
"../../../bd/zusys/ip/zusys_ila_tx_0_0/sim/zusys_ila_tx_0_0.vhd" \
"../../../bd/zusys/sim/zusys.vhd" \

vlog -work axis_infrastructure_v1_1_0 -64 -incr "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl/axis_infrastructure_v1_1_vl_rfs.v" \

vlog -work axis_register_slice_v1_1_15 -64 -incr "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cd45/hdl/axis_register_slice_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zusys/ip/zusys_auto_ss_k_1/hdl/tdata_zusys_auto_ss_k_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_k_1/hdl/tuser_zusys_auto_ss_k_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_k_1/hdl/tstrb_zusys_auto_ss_k_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_k_1/hdl/tkeep_zusys_auto_ss_k_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_k_1/hdl/tid_zusys_auto_ss_k_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_k_1/hdl/tdest_zusys_auto_ss_k_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_k_1/hdl/tlast_zusys_auto_ss_k_1.v" \

vlog -work axis_subset_converter_v1_1_15 -64 -incr "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6ad2/hdl/axis_subset_converter_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zusys/ip/zusys_auto_ss_k_1/hdl/top_zusys_auto_ss_k_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_k_1/sim/zusys_auto_ss_k_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_slid_1/hdl/tdata_zusys_auto_ss_slid_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_slid_1/hdl/tuser_zusys_auto_ss_slid_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_slid_1/hdl/tstrb_zusys_auto_ss_slid_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_slid_1/hdl/tkeep_zusys_auto_ss_slid_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_slid_1/hdl/tid_zusys_auto_ss_slid_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_slid_1/hdl/tdest_zusys_auto_ss_slid_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_slid_1/hdl/tlast_zusys_auto_ss_slid_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_slid_1/hdl/top_zusys_auto_ss_slid_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_slid_1/sim/zusys_auto_ss_slid_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_u_1/hdl/tdata_zusys_auto_ss_u_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_u_1/hdl/tuser_zusys_auto_ss_u_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_u_1/hdl/tstrb_zusys_auto_ss_u_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_u_1/hdl/tkeep_zusys_auto_ss_u_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_u_1/hdl/tid_zusys_auto_ss_u_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_u_1/hdl/tdest_zusys_auto_ss_u_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_u_1/hdl/tlast_zusys_auto_ss_u_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_u_1/hdl/top_zusys_auto_ss_u_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_u_1/sim/zusys_auto_ss_u_1.v" \
"../../../bd/zusys/ip/zusys_auto_ss_k_0/hdl/tdata_zusys_auto_ss_k_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_k_0/hdl/tuser_zusys_auto_ss_k_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_k_0/hdl/tstrb_zusys_auto_ss_k_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_k_0/hdl/tkeep_zusys_auto_ss_k_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_k_0/hdl/tid_zusys_auto_ss_k_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_k_0/hdl/tdest_zusys_auto_ss_k_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_k_0/hdl/tlast_zusys_auto_ss_k_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_k_0/hdl/top_zusys_auto_ss_k_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_k_0/sim/zusys_auto_ss_k_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_slid_0/hdl/tdata_zusys_auto_ss_slid_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_slid_0/hdl/tuser_zusys_auto_ss_slid_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_slid_0/hdl/tstrb_zusys_auto_ss_slid_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_slid_0/hdl/tkeep_zusys_auto_ss_slid_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_slid_0/hdl/tid_zusys_auto_ss_slid_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_slid_0/hdl/tdest_zusys_auto_ss_slid_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_slid_0/hdl/tlast_zusys_auto_ss_slid_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_slid_0/hdl/top_zusys_auto_ss_slid_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_slid_0/sim/zusys_auto_ss_slid_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_u_0/hdl/tdata_zusys_auto_ss_u_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_u_0/hdl/tuser_zusys_auto_ss_u_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_u_0/hdl/tstrb_zusys_auto_ss_u_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_u_0/hdl/tkeep_zusys_auto_ss_u_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_u_0/hdl/tid_zusys_auto_ss_u_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_u_0/hdl/tdest_zusys_auto_ss_u_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_u_0/hdl/tlast_zusys_auto_ss_u_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_u_0/hdl/top_zusys_auto_ss_u_0.v" \
"../../../bd/zusys/ip/zusys_auto_ss_u_0/sim/zusys_auto_ss_u_0.v" \

vlog -work generic_baseblocks_v2_1_0 -64 -incr "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_data_fifo_v2_1_14 -64 -incr "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/9909/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_15 -64 -incr "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/3ed1/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_protocol_converter_v2_1_15 -64 -incr "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ff69/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/ec67/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/02c8/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/e2dd/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/0ab1/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6180/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/a08d/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/4962/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/bb93/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/cfaa/hdl" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/6851/hdl/verilog" "+incdir+../../../../te0808_project.srcs/sources_1/bd/zusys/ipshared/82bb/hdl/verilog" "+incdir+/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zusys/ip/zusys_auto_pc_0/sim/zusys_auto_pc_0.v" \

vlog -work xil_defaultlib \
"glbl.v"

